export enum SelectEnum {

  COULEUR = 'SELECTIONNER UNE COULEUR',
  TRANSMISSION = 'SELECTIONNER UNE TRANSMISSION',
  ENERGIE = 'SELECTIONNER UNE ENERGIE',
  ETAT = 'SELECTIONNER UN ETAT',
  MARQUE = 'SELECTIONNER UNE MARQUE',
  TYPE_VEHICULE = 'SELECTIONNER UN TYPE DE VEHICULE',

}
